src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 *
 * Defines the properties of the Event entity to represent the website events.
 * @author Florian Mornet <florian.mornet@enseirb-matmeca.fr>
 */
class Event
{
    /**
     * @var int
     *
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(max = 255, maxMessage = "The event name cannot be longer than {{ limit }} characters.")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max = 255, maxMessage = "The event location cannot be longer than {{ limit }} characters.")
     */
    private $location;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max = 255, maxMessage = "The event category cannot be longer than {{ limit }} characters.")
     */
    private $category;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(max = 255, maxMessage = "The event hoster cannot be longer than {{ limit }} characters.")
     */
    private $hoster;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $poster;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="date")
     * @Assert\NotBlank()
     * @Assert\Type("\DateTime")
     */
    private $date_start;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="date", nullable=true)
     * @Assert\Type("\DateTime")
     */
    private $date_end;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="time")
     * @Assert\NotBlank()
     * @Assert\Type("\DateTime")
     */
    private $time_start;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="time", nullable=true)
     * @Assert\Type("\DateTime")
     */
    private $time_end;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=10, nullable=true)
     * @Assert\Length(max = 10, maxMessage = "The phone number cannot be longer than {{ limit }} characters.")
     */
    private $phone;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email(message = "The email {{ value }} is not a valid email.")
     * @Assert\Length(max = 255, maxMessage = "The email address cannot be longer than {{ limit }} characters.")
     */
    private $email;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getHoster(): ?string
    {
        return $this->hoster;
    }

    public function setHoster(string $hoster): self
    {
        $this->hoster = $hoster;

        return $this;
    }

    public function getPoster(): ?User
    {
        return $this->poster;
    }

    public function setPoster(User $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(?\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getTimeStart(): ?\DateTimeInterface
    {
        return $this->time_start;
    }

    public function setTimeStart(\DateTimeInterface $time_start): self
    {
        $this->time_start = $time_start;

        return $this;
    }

    public function getTimeEnd(): ?\DateTimeInterface
    {
        return $this->time_end;
    }

    public function setTimeEnd(?\DateTimeInterface $time_end): self
    {
        $this->time_end = $time_end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Defines the form used to create and manipulate events.
 * @author Florian Mornet <florian.mornet@enseirb-matmeca.fr>
 */
class EventType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, array('label' => 'Event name'))
            ->add('location', TextType::class, array('label' => 'Event location (optional)', 'required' => false))
            ->add('category', TextType::class, array('label' => 'Category (optional)', 'required' => false))
            ->add('hoster', TextType::class, array('label' => 'Event hoster'))
            ->add('date_start', DateType::class, array('label' => 'Date when this event starts', 'widget' => 'single_text'))
            ->add('date_end', DateType::class, array('label' => 'Date when this event ends (optional)', 'widget' => 'single_text', 'required' => false))
            ->add('time_start', TimeType::class, array('label' => 'Time when this event starts', 'widget' => 'single_text'))
            ->add('time_end', TimeType::class, array('label' => 'Time when this event ends (optional)', 'widget' => 'single_text', 'required' => false))
            ->add('description', TextareaType::class, array('label' => 'Description', 'required' => false))
            ->add('phone', TelType::class, array('label' => 'Phone number to call (optional)', 'required' => false))
            ->add('email', EmailType::class, array('label' => 'Contact email address'))
            ->add('save', SubmitType::class, array('label' => 'Add'))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Form\EventType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Event;

/**
 * Controller used to manage events.
 * @author Florian Mornet <florian.mornet@enseirb-matmeca.fr>
 */
class EventController extends AbstractController
{
    /**
     * Returns the number of events a user added.
     *
     * @return int|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    private function getUserEventCount()
    {
        $event_count = null;
        if ($this->container->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            $event_count = $this->getDoctrine()->getRepository(Event::class)->countEventsByUser($this->getUser());
        }
        return $event_count;
    }

    /**
     * @Route("/", name="events")
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function index()
    {
        // Find all events, ascending according to the start date and start time
        $events=$this->getDoctrine()->getRepository(Event::class)->findBy(array(), array('date_start' => 'asc', 'time_start' => 'asc'));

        return $this->render('event/base_list_events.html.twig', [
            'controller_name' => 'EventController',
            'events' => $events,
            'event_count' => $this->getUserEventCount(),
        ]);
    }

    /**
     * @Route("/event/{id}", name="event_detail", requirements={"id"="\d+"})
     * @param mixed $id The identifier.
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function detail($id)
    {
        // Find $id event
        $event = $this->getDoctrine()->getRepository(Event::class)->find($id);

        return $this->render('event/event.html.twig', [
            'event' => $event,
            'event_count' => $this->getUserEventCount(),
        ]);
    }

    /**
     * @Route("/event/new", name="add_event")
     * @Security("has_role('ROLE_USER')")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function addEvent(Request $request)
    {
        // 1) build the form
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $event->setPoster($this->getUser());

        // 2) handle the submit (will only happen on POST)
        // Link between form and request object
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){

            // 3) Save new event
            $em = $this->getDoctrine()->getManager();
            $em->persist($event);
            $em->flush();
            return $this->redirectToRoute('events');
        }

        return $this->render('event/add_event.html.twig', [
            'form' => $form->createView(),
            'event_count' => $this->getUserEventCount(),
        ]);
    }

    /**
     * @Route("/event/{id}/delete", name="delete_event", requirements={"id"="\d+"})
     * @param mixed $id The identifier.
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteEvent($id)
    {
        // Find $id event
        $event = $this->getDoctrine()->getRepository(Event::class)->find($id);

        // Remove event from database if the logged in user is the one who posted the event
        if($event->getPoster() === $this->getUser()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($event);
            $em->flush();
        }

        return $this->redirectToRoute('my_events');
    }

    /**
     * @Route("/my_events", name="my_events")
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function myEvents()
    {
        // Find all events by the connected user
        $eventsUser = $this->getDoctrine()->getRepository(Event::class)->findByUser($this->getUser());

        return $this->render('event/my_events.html.twig', [
            'controller_name' => 'EventController',
            'action_name' => 'my_events',
            'events' => $eventsUser,
            'event_count' => $this->getUserEventCount(),
        ]);
    }
}

templates/event/add.html.twig
{#
   This is the form template to add a new event.
#}
{% extends 'base.html.twig' %}

{% block title %}New event | Meetdown.io{% endblock %}

{% block body %}
    <section class="jumbotron" xmlns="http://www.w3.org/1999/html">
        <h2 class="jumbotron-heading">Add a new event</h2>
        {{ form(form) }}
    </section>
{% endblock %}

templates/event/add_event.html.twig
{#
   This is the form template to add a new event.
#}
{% extends 'base.html.twig' %}

{% block title %}New event | Meetdown.io{% endblock %}

{% block body %}
    <section class="jumbotron" xmlns="http://www.w3.org/1999/html">
        <h2 class="jumbotron-heading">Add a new event</h2>
        {{ form(form) }}
    </section>
{% endblock %}

templates/event/base_list_events.html.twig
{#
   This is the base list of events template, displaying events.
#}
{% extends 'base.html.twig' %}

{% block body %}
    {% if events %}
        <div class="row">
            {% for event in events %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <a href="event/{{ event.id }}">
                        <img class="card-img-top" data-src="holder.js/100px225?theme=event{{ event.id }}&text={{ event.name }} \n on {{ event.dateStart|date('M d, Y') }}{% if event.location %} \n at {{ event.location }} {% endif %}" alt="Card image cap">
                    </a>
                    <div class="card-body">
                        <p class="card-text">{{ event.description|length > 255 ? event.description|slice(0, 255)|split(' ')|slice(0, -1)|join(' ') ~ ' […]' : event.description }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-success" href="event/{{ event.id }}">Details</a>
                                {% block event %}{% endblock %}
                            </div>
                            <small class="text-muted">by {{ event.poster.fullName }}</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <section class="jumbotron" xmlns="http://www.w3.org/1999/html">
            <h2 class="jumbotron-heading text-center">{% block noevents %}There are no events!{% endblock %} Click <a href="/event/new">here</a> to add one.</h2>
        </section>
    {% endif %}
{% endblock %}

{% block javascripts %}
    <script>
        // Generates a dark random color (hex between 0 and 9)
        function getRandomColor() {
            const letters = '0123456789';
            let color = '#';
            for (let i = 0; i < 3; i++) {
                color += letters[Math.floor(Math.random() * 10)];
            }
            return color;
        }

        {% for event in events %}
            Holder.addTheme("event{{ event.id }}", {
                bg: getRandomColor(), fg: "#eceeef"
            });
            {% endfor %}
    </script>
{% endblock %}

templates/event/event.html.twig
{#
   This is the event template, displaying all event details.
#}
{% extends 'base.html.twig' %}

{% block title %}{{ event.name|e }} | Meetdown.io{% endblock %}

{% block body %}
    <section class="jumbotron" xmlns="http://www.w3.org/1999/html">
        {% if event.dateEnd %}
            {% if event.timeEnd %}
                <h2 class="jumbotron-heading">From {{ event.dateStart|date('l, M d, Y') }} to {{ event.dateEnd|date('l, M d, Y') }}</h2>
                <h2 class="jumbotron-heading">{{ event.timeStart|date('H:i') }}-{{ event.timeStart|date('H:i') }}</h2>
            {% else %}
                <h2>From {{ event.dateStart|date('l, M d, Y') }} to {{ event.dateEnd|date('l, M d, Y') }} at {{ event.timeStart|date('H:i') }}</h2>
            {% endif %}
        {% else %}
            {% if event.timeEnd %}
                <h2 class="jumbotron-heading">{{ event.dateStart|date('l, M d, Y') }}, from {{ event.timeStart|date('H:i') }} to {{ event.timeStart|date('H:i') }}</h2>
            {% else %}
                <h2 class="jumbotron-heading">{{ event.dateStart|date('l, M d, Y') }} at {{ event.timeStart|date('H:i') }}</h2>
            {% endif %}
        {% endif %}

        <h2>
            {{ event.name }}
            {% if event.location %}
                at <a href="https://www.google.com/maps/search/?api=1&query={{ event.location|e('url') }}">{{ event.location }}</a>
            {% endif %}
            {% if event.category %}
                <span class="badge badge-secondary float-right">{{ event.category }}</span>
            {% endif %}
        </h2>
        <hr class="container">

        {% if event.description %}
            <p class="lead text-muted">{{ event.description }}</p>
        {% endif %}

        <p class="text-muted">Hosted by {{ event.hoster }}, added by {{ event.poster.fullName }}.</p>
        <div class="text-center">
            <div class="btn-group">
                {% if event.phone %}
                    <a href="tel:{{ event.phone }}" class="btn btn-outline-success my-2">Phone: {{ event.phone }}</a>
                {% endif %}
                <a href="mailto:{{ event.phone }}" class="btn btn-outline-success my-2">Email: {{ event.email }}</a>
            </div>
        </div>
    </section>
{% endblock %}

templates/event/index.html.twig
{#
   This is the main index template, displaying all events.
#}
{% extends 'base.html.twig' %}

{% block title %}Meetdown.io{% endblock %}

{% block body %}
<div class="row">
    {% for event in events %}
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <a href="event/{{ event.id }}">
                <img class="card-img-top" data-src="holder.js/100px225?theme=event{{ event.id }}&text={{ event.name }} \n on {{ event.dateStart|date('M d, Y') }}{% if event.location %} \n at {{ event.location }} {% endif %}" alt="Card image cap">
            </a>
            <div class="card-body">
                <p class="card-text">{{ event.description|length > 255 ? event.description|slice(0, 255)|split(' ')|slice(0, -1)|join(' ') ~ ' […]' : event.description }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <a class="btn btn-sm btn-outline-success" href="event/{{ event.id }}">Details</a>
                    <small class="text-muted">by {{ event.poster }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block javascripts %}
<script>
    // Generates a dark random color (hex between 0 and 9)
    function getRandomColor() {
        var letters = '0123456789';
        var color = '#';
        for (var i = 0; i < 3; i++) {
            color += letters[Math.floor(Math.random() * 10)];
        }
        return color;
    }

    {% for event in events %}
    Holder.addTheme("event{{ event.id }}", {
        bg: getRandomColor(), fg: "#eceeef"
    });
    {% endfor %}
</script>
{% endblock %}

templates/event/my_events.html.twig
{#
   This is the template used to display all user events.
#}
{% extends 'event/base_list_events.html.twig' %}

{% block title %}My events | Meetdown.io{% endblock %}

{% block headertitle %}Meetdown.io - My events {% if event_count %}({{ event_count }}){% endif %}{% endblock %}

{% block noevents %}You don't have any events!{% endblock %}

{% block event %}
    <a class="btn btn-sm btn-outline-danger" href="event/{{ event.id }}/delete">Delete</a>
{% endblock %}